# Generated by Django 6.0.3 on 2026-03-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd', '0002_alter_crowdrecord_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdrecord',
            name='station',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
