# Generated by Django 6.0.3 on 2026-03-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd', '0003_alter_crowdrecord_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdrecord',
            name='station',
            field=models.CharField(max_length=100),
        ),
    ]
