# Generated by Django 6.0.3 on 2026-03-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd', '0004_alter_crowdrecord_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
